# Databricks notebook source
# MAGIC %run ./_setup

# COMMAND ----------

# MAGIC %md
# MAGIC # Google Drive to Databricks with brickbyte
# MAGIC 
# MAGIC This notebook syncs files from Google Drive to Delta Lake tables in Unity Catalog.
# MAGIC 
# MAGIC **Supported file formats:** CSV, JSON, Parquet, Avro, JSONL, Excel, Feather
# MAGIC 
# MAGIC **Prerequisites:**
# MAGIC - A Google Cloud service account with access to your Drive folder
# MAGIC - The folder must be shared with your service account email

# COMMAND ----------

import brickbyte

bb = brickbyte.client()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration
# MAGIC 
# MAGIC 1. Get your **Service Account Key** from Google Cloud Console
# MAGIC 2. Get the **Folder Link** from Google Drive (share the folder with your service account)

# COMMAND ----------

# Your Google Cloud service account credentials (JSON format)
# Store this in Databricks Secrets for production use:
#   service_account_key = dbutils.secrets.get(scope="google", key="service_account_json")

service_account_key = """
{
  "type": "service_account",
  "project_id": "YOUR_PROJECT_ID",
  "private_key_id": "YOUR_PRIVATE_KEY_ID",
  "private_key": "YOUR_PRIVATE_KEY_PEM_CONTENT",
  "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
  "client_id": "123456789",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token"
}
"""

# The Google Drive folder link (the folder must be shared with your service account)
folder_link = "https://drive.google.com/drive/folders/YOUR_FOLDER_ID"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sync CSV/JSON Files from Google Drive

# COMMAND ----------

import json

result = bb.sync(
    source="source-google-drive",
    source_config={
        "folder_url": folder_link,
        "credentials": {
            "auth_type": "Service",
            "service_account_info": service_account_key,
        },
        # File format configuration for CSV files
        "streams": [
            {
                "name": "my_csv_files",
                "globs": ["**/*.csv"],
                "format": {
                    "filetype": "csv",
                    "delimiter": ",",
                    "header_definition": {"header_definition_type": "Autogenerated"},
                },
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records from {len(result.streams_synced)} streams")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sync JSON Files

# COMMAND ----------

result = bb.sync(
    source="source-google-drive",
    source_config={
        "folder_url": folder_link,
        "credentials": {
            "auth_type": "Service",
            "service_account_info": service_account_key,
        },
        "streams": [
            {
                "name": "json_data",
                "globs": ["**/*.json"],
                "format": {"filetype": "jsonl"},
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sync Parquet Files (No Format Config Needed)

# COMMAND ----------

result = bb.sync(
    source="source-google-drive",
    source_config={
        "folder_url": folder_link,
        "credentials": {
            "auth_type": "Service",
            "service_account_info": service_account_key,
        },
        "streams": [
            {
                "name": "parquet_data",
                "globs": ["**/*.parquet"],
                "format": {"filetype": "parquet"},
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sync All Supported Files (Wildcard Pattern)

# COMMAND ----------

result = bb.sync(
    source="source-google-drive",
    source_config={
        "folder_url": folder_link,
        "credentials": {
            "auth_type": "Service",
            "service_account_info": service_account_key,
        },
        "streams": [
            {
                "name": "all_files",
                "globs": ["**/*"],  # All files recursively
                "format": {"filetype": "unstructured"},
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records")

# COMMAND ----------

# MAGIC %md
# MAGIC ## With AI Metadata Enrichment

# COMMAND ----------

# Sync with automatic AI-powered metadata generation
# result = bb.sync(
#     source="source-google-drive",
#     source_config={
#         "folder_url": folder_link,
#         "credentials": {
#             "auth_type": "Service",
#             "service_account_info": service_account_key,
#         },
#         "streams": [
#             {
#                 "name": "csv_with_enrichment",
#                 "globs": ["**/*.csv"],
#                 "format": {"filetype": "csv"},
#             }
#         ],
#     },
#     catalog="",  # TODO: Set your Unity Catalog name
#     schema="",   # TODO: Set your target schema
#     enrich_metadata=True,
#     enrich_model="databricks-meta-llama-3-3-70b-instruct",
# )

# print(f"Enriched tables: {result.enriched_tables}")
