# Databricks notebook source
# MAGIC %run ./_setup

# COMMAND ----------

# MAGIC %md
# MAGIC # Google Cloud Storage (GCS) to Databricks with BrickByte
# MAGIC 
# MAGIC This notebook syncs files from Google Cloud Storage to Delta Lake tables in Unity Catalog.
# MAGIC 
# MAGIC **Supported file formats:** CSV, JSON, Parquet, Avro, JSONL
# MAGIC 
# MAGIC **Prerequisites:**
# MAGIC - GCS bucket name
# MAGIC - Service Account with `Storage Object Viewer` role
# MAGIC - Service Account Key (JSON)

# COMMAND ----------

from brickbyte import BrickByte

bb = BrickByte()

# COMMAND ----------

# MAGIC %md
# MAGIC ## Configuration
# MAGIC 
# MAGIC 1. Create a Service Account in Google Cloud Console
# MAGIC 2. Grant `Storage Object Viewer` role on your bucket
# MAGIC 3. Generate a JSON key for the service account

# COMMAND ----------

# Your Google Cloud service account credentials (JSON format)
# Store in Databricks Secrets for production:
#   service_account_key = dbutils.secrets.get(scope="gcp", key="service_account_json")

service_account_key = """
{
  "type": "service_account",
  "project_id": "YOUR_PROJECT_ID",
  "private_key_id": "YOUR_PRIVATE_KEY_ID",
  "private_key": "YOUR_PRIVATE_KEY_PEM_CONTENT",
  "client_email": "your-service-account@your-project.iam.gserviceaccount.com",
  "client_id": "123456789",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token"
}
"""

bucket_name = "your-gcs-bucket"

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sync CSV Files from GCS

# COMMAND ----------

result = bb.sync(
    source="source-gcs",
    source_config={
        "gcs_bucket": bucket_name,
        "gcs_path": "",  # Root of bucket, or specify a prefix like "data/"
        "service_account": service_account_key,
        "streams": [
            {
                "name": "csv_files",
                "globs": ["**/*.csv"],
                "format": {
                    "filetype": "csv",
                    "delimiter": ",",
                    "header_definition": {"header_definition_type": "Autogenerated"},
                },
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records from {len(result.streams_synced)} streams")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sync Parquet Files

# COMMAND ----------

result = bb.sync(
    source="source-gcs",
    source_config={
        "gcs_bucket": bucket_name,
        "service_account": service_account_key,
        "streams": [
            {
                "name": "parquet_data",
                "globs": ["**/*.parquet"],
                "format": {"filetype": "parquet"},
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sync JSON Lines Files

# COMMAND ----------

result = bb.sync(
    source="source-gcs",
    source_config={
        "gcs_bucket": bucket_name,
        "service_account": service_account_key,
        "streams": [
            {
                "name": "json_events",
                "globs": ["events/**/*.jsonl", "logs/**/*.json"],
                "format": {"filetype": "jsonl"},
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Sync Avro Files

# COMMAND ----------

result = bb.sync(
    source="source-gcs",
    source_config={
        "gcs_bucket": bucket_name,
        "service_account": service_account_key,
        "streams": [
            {
                "name": "avro_data",
                "globs": ["**/*.avro"],
                "format": {"filetype": "avro"},
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records")

# COMMAND ----------

# MAGIC %md
# MAGIC ## Multiple Streams from Different Paths

# COMMAND ----------

result = bb.sync(
    source="source-gcs",
    source_config={
        "gcs_bucket": bucket_name,
        "service_account": service_account_key,
        "streams": [
            {
                "name": "raw_sales",
                "globs": ["raw/sales/**/*.csv"],
                "format": {"filetype": "csv"},
            },
            {
                "name": "processed_analytics",
                "globs": ["processed/analytics/**/*.parquet"],
                "format": {"filetype": "parquet"},
            },
            {
                "name": "event_logs",
                "globs": ["logs/**/*.jsonl"],
                "format": {"filetype": "jsonl"},
            },
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records from: {result.streams_synced}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## With Start Date Filter (Incremental)

# COMMAND ----------

result = bb.sync(
    source="source-gcs",
    source_config={
        "gcs_bucket": bucket_name,
        "service_account": service_account_key,
        "start_date": "2024-01-01T00:00:00Z",  # Only files modified after this date
        "streams": [
            {
                "name": "recent_data",
                "globs": ["**/*.parquet"],
                "format": {"filetype": "parquet"},
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
)

print(f"Synced {result.records_written} records")

# COMMAND ----------

# MAGIC %md
# MAGIC ## With AI Metadata Enrichment

# COMMAND ----------

result = bb.sync(
    source="source-gcs",
    source_config={
        "gcs_bucket": bucket_name,
        "service_account": service_account_key,
        "streams": [
            {
                "name": "customer_data",
                "globs": ["customers/**/*.csv"],
                "format": {"filetype": "csv"},
            }
        ],
    },
    catalog="",  # TODO: Set your Unity Catalog name
    schema="",   # TODO: Set your target schema
    enrich_metadata=True,
    enrich_model="databricks-meta-llama-3-1-70b-instruct",
)

print(f"Enriched tables: {result.enriched_tables}")
